In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
print("Numpy version:", np.__version__)

Numpy version: 2.5.4

In [4]:
print("Pandas version:", pd.__version__)

Pandas version: 3.1.0

In [5]:
df=pd.read_csv("ev_charging_sessions.csv")

In [6]:
print(df)

       Session_Start Session_ID       City             Area Charger_Type  \
0   2026-09-01 07:42     EVS001    Chennai          T Nagar      Fast DC
1   2026-09-01 08:10     EVS002  Bengaluru      Indiranagar           AC
2   2026-09-01 09:25     EVS003  Hyderabad      Hitech City      Fast DC
3   2026-09-01 10:03     EVS004       Pune        Hinjewadi           AC
4   2026-09-01 11:48     EVS005     Mumbai              BKC      Fast DC
5   2026-09-01 12:16     EVS006    Chennai              OMR           AC
6   2026-09-01 13:40     EVS007      Delhi            Saket      Fast DC
7   2026-09-01 14:05     EVS008      Kochi         Kakkanad           AC
8   2026-09-01 15:32     EVS009  Bengaluru       Whitefield      Fast DC
9   2026-09-01 16:11     EVS010    Chennai            Adyar           AC
10  2026-09-02 07:35     EVS011  Hyderabad       Gachibowli      Fast DC
11  2026-09-02 08:52     EVS012       Pune    Koregaon Park           AC
12  2026-09-02 09:44     EVS013     Mumbai          Andheri      Fast DC
13  2026-09-02 10:28     EVS014      Delhi           Dwarka           AC
14  2026-09-02 11:19     EVS015      Kochi       Fort Kochi      Fast DC
15  2026-09-02 12:47     EVS016    Chennai        Velachery           AC
16  2026-09-02 13:26     EVS017  Bengaluru  Electronic City      Fast DC
17  2026-09-02 14:51     EVS018  Hyderabad         Madhapur           AC
18  2026-09-02 15:37     EVS019       Pune            Wakad      Fast DC
19  2026-09-02 17:04     EVS020     Mumbai            Powai           AC
20  2026-09-03 07:58     EVS021      Delhi  Connaught Place      Fast DC
21  2026-09-03 08:31     EVS022    Chennai           Guindy           AC
22  2026-09-03 09:17     EVS023      Kochi        Edappally      Fast DC
23  2026-09-03 10:46     EVS024  Bengaluru      Koramangala           AC
24  2026-09-03 11:54     EVS025  Hyderabad         Kondapur      Fast DC
25  2026-09-03 12:22     EVS026       Pune            Baner           AC
26  2026-09-03 13:49     EVS027     Mumbai      Lower Parel      Fast DC
27  2026-09-03 14:33     EVS028      Delhi           Rohini           AC
28  2026-09-03 16:02     EVS029    Chennai       Anna Nagar      Fast DC
29  2026-09-03 17:26     EVS030  Bengaluru        Jayanagar           AC

    Energy_Delivered_kWh  Duration_Minutes  Session_Cost_INR  \
0                   42.5              18.2               774
1                   11.0               6.4               231
2                   55.0              25.1              1067
3                    9.5               5.2               187
4                   36.0              16.8               714
5                   13.0               7.1               256
6                   48.0              22.7               965
7                    7.0               3.8               137
8                   51.5              23.6              1003
9                   10.5               5.9               212
10                  44.0              20.4               867
11                  12.0               6.8               245
12                   0.0               0.0                 0
13                   8.5               4.6               166
14                  32.0              14.5               616
15                  14.0               7.6               274
16                  59.0              27.8              1182
17                   6.5               3.4               122
18                  39.0              18.1               769
19                  10.0               5.7               205
20                  46.0              21.9               931
21                   9.0               4.8               173
22                  34.5              15.9               676
23                  15.0               8.2               295
24                   0.0               0.0                 0
25                  11.5               6.3               227
26                  53.0              24.8              1054
27                   7.5               4.1               148
28                  41.0              19.3               820
29                  12.5               6.9               248

    Wait_Time_Minutes  Battery_End_Percent  Estimated_CO2_Saved_kg  \
0                  38                   82                     6.8
1                  22                   74                     3.1
2                  19                   91                     8.4
3                  47                   69                     2.7
4                  31                   77                     6.2
5                  16                   88                     3.5
6                  53                   84                     7.5
7                  12                   61                     2.1
8                  28                   93                     8.1
9                  24                   72                     2.9
10                 17                   86                     7.0
11                 39                   79                     3.3
12                  0                   42                     0.0
13                 26                   65                     2.4
14                 14                   81                     5.4
15                 33                   90                     3.8
16                 44                   96                     9.0
17                 21                   58                     1.9
18                 36                   83                     6.4
19                 49                   71                     2.8
20                 61                   89                     7.3
21                 18                   67                     2.5
22                 23                   80                     5.8
23                 27                   94                     4.0
24                  0                   36                     0.0
25                 15                   76                     3.2
26                 42                   92                     8.6
27                 34                   63                     2.2
28                 29                   85                     6.7
29                 51                   78                     3.4

    Charger_Power_kW  Customer_Rating_5  Grid_Load_Impact_kW Payment_Method  \
0               24.5                4.2                  1.8            App
1                8.0                2.8                  0.4           RFID
2               31.0                5.0                  2.6            App
3                6.5                2.2                  0.3             QR
4               21.0                4.6                  1.4            App
5                9.0                2.9                  0.5           RFID
6               28.0                4.8                  2.2            App
7                4.5                2.0                  0.2             QR
8               30.0                5.0                  2.5            App
9                7.0                2.6                  0.4           RFID
10              26.0                4.4                  2.0            App
11               8.5                2.7                  0.4             QR
12               0.0                0.0                  0.0            App
13               5.5                2.1                  0.3           RFID
14              18.0                4.0                  1.2            App
15               9.5                3.0                  0.5             QR
16              34.0                5.3                  2.8            App
17               4.0                1.9                  0.2           RFID
18              23.0                4.5                  1.6            App
19               6.5                2.5                  0.3             QR
20              27.0                4.9                  2.1            App
21               6.0                2.3                  0.3           RFID
22              20.0                4.1                  1.3            App
23              10.0                3.1                  0.5             QR
24               0.0                0.0                  0.0           RFID
25               7.5                2.6                  0.4            App
26              32.0                5.2                  2.7            App
27               5.0                2.0                  0.2             QR
28              24.0                4.3                  1.7           RFID
29               8.5                2.8                  0.4            App

   Session_Status
0       Completed
1       Completed
2       Completed
3       Completed
4       Completed
5       Completed
6       Completed
7       Completed
8       Completed
9       Completed
10      Completed
11      Completed
12         Failed
13      Completed
14      Completed
15      Completed
16      Completed
17    Interrupted
18      Completed
19      Completed
20      Completed
21      Completed
22      Completed
23      Completed
24         Failed
25      Completed
26      Completed
27    Interrupted
28      Completed
29      Completed

In [7]:
df.head(3)

,Session_Start,Session_ID,City,Area,Charger_Type,Energy_Delivered_kWh,Duration_Minutes,Session_Cost_INR,Wait_Time_Minutes,Battery_End_Percent,Estimated_CO2_Saved_kg,Charger_Power_kW,Customer_Rating_5,Grid_Load_Impact_kW,Payment_Method,Session_Status
0,2026-09-01 07:42,EVS001,Chennai,T Nagar,Fast DC,42.5,18.2,774,38,82,6.8,24.5,4.2,1.8,App,Completed
1,2026-09-01 08:10,EVS002,Bengaluru,Indiranagar,AC,11.0,6.4,231,22,74,3.1,8.0,2.8,0.4,RFID,Completed
2,2026-09-01 09:25,EVS003,Hyderabad,Hitech City,Fast DC,55.0,25.1,1067,19,91,8.4,31.0,5.0,2.6,App,Completed

In [8]:
df.tail(3)

,Session_Start,Session_ID,City,Area,Charger_Type,Energy_Delivered_kWh,Duration_Minutes,Session_Cost_INR,Wait_Time_Minutes,Battery_End_Percent,Estimated_CO2_Saved_kg,Charger_Power_kW,Customer_Rating_5,Grid_Load_Impact_kW,Payment_Method,Session_Status
27,2026-09-03 14:33,EVS028,Delhi,Rohini,AC,7.5,4.1,148,34,63,2.2,5.0,2.0,0.2,QR,Interrupted
28,2026-09-03 16:02,EVS029,Chennai,Anna Nagar,Fast DC,41.0,19.3,820,29,85,6.7,24.0,4.3,1.7,RFID,Completed
29,2026-09-03 17:26,EVS030,Bengaluru,Jayanagar,AC,12.5,6.9,248,51,78,3.4,8.5,2.8,0.4,App,Completed

In [9]:
df.shape

(30, 16)

In [10]:
df.columns

Index(['Session_Start', 'Session_ID', 'City', 'Area', 'Charger_Type',
       'Energy_Delivered_kWh', 'Duration_Minutes', 'Session_Cost_INR',
       'Wait_Time_Minutes', 'Battery_End_Percent', 'Estimated_CO2_Saved_kg',
       'Charger_Power_kW', 'Customer_Rating_5', 'Grid_Load_Impact_kW',
       'Payment_Method', 'Session_Status'],
      dtype='str')

In [11]:
df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Session_Start           30 non-null     str
 1   Session_ID              30 non-null     str
 2   City                    30 non-null     str
 3   Area                    30 non-null     str
 4   Charger_Type            30 non-null     str
 5   Energy_Delivered_kWh    30 non-null     float64
 6   Duration_Minutes        30 non-null     float64
 7   Session_Cost_INR        30 non-null     int64
 8   Wait_Time_Minutes       30 non-null     int64
 9   Battery_End_Percent     30 non-null     int64
 10  Estimated_CO2_Saved_kg  30 non-null     float64
 11  Charger_Power_kW        30 non-null     float64
 12  Customer_Rating_5       30 non-null     float64
 13  Grid_Load_Impact_kW     30 non-null     float64
 14  Payment_Method          30 non-null     str
 15  Session_Status          30 non-null     str
dtypes: float64(6), int64(3), str(7)
memory usage: 3.9 KB

,Energy_Delivered_kWh,Duration_Minutes,Session_Cost_INR,Wait_Time_Minutes,Battery_End_Percent,Estimated_CO2_Saved_kg,Charger_Power_kW,Customer_Rating_5,Grid_Load_Impact_kW
count,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.00000
mean,24.633333,11.863333,485.466667,28.966667,76.733333,4.566667,14.816667,3.260000,1.04000
std,18.921313,8.451994,372.779748,15.075633,14.552955,2.564793,10.685539,1.426014,0.92386
min,0.000000,0.000000,0.000000,0.000000,36.000000,0.000000,0.000000,0.000000,0.00000
25%,9.625000,5.325000,191.500000,18.250000,69.500000,2.725000,6.500000,2.350000,0.30000
50%,13.500000,7.350000,265.000000,27.500000,79.500000,3.650000,9.250000,2.950000,0.50000
75%,42.125000,19.025000,808.500000,38.750000,87.500000,6.775000,24.375000,4.475000,1.77500
max,59.000000,27.800000,1182.000000,61.000000,96.000000,9.000000,34.000000,5.300000,2.80000

In [12]:
df.isnull().sum()

Session_Start             0
Session_ID                0
City                      0
Area                      0
Charger_Type              0
Energy_Delivered_kWh      0
Duration_Minutes          0
Session_Cost_INR          0
Wait_Time_Minutes         0
Battery_End_Percent       0
Estimated_CO2_Saved_kg    0
Charger_Power_kW          0
Customer_Rating_5         0
Grid_Load_Impact_kW       0
Payment_Method            0
Session_Status            0
dtype: int64

In [13]:
df.isnull().count()

Session_Start             30
Session_ID                30
City                      30
Area                      30
Charger_Type              30
Energy_Delivered_kWh      30
Duration_Minutes          30
Session_Cost_INR          30
Wait_Time_Minutes         30
Battery_End_Percent       30
Estimated_CO2_Saved_kg    30
Charger_Power_kW          30
Customer_Rating_5         30
Grid_Load_Impact_kW       30
Payment_Method            30
Session_Status            30
dtype: int64

In [14]:
df.unique()

AttributeError: 'DataFrame' object has no attribute 'unique'

In [15]:
df.nunique()

Session_Start             30
Session_ID                30
City                       7
Area                      30
Charger_Type               2
Energy_Delivered_kWh      29
Duration_Minutes          29
Session_Cost_INR          29
Wait_Time_Minutes         29
Battery_End_Percent       30
Estimated_CO2_Saved_kg    29
Charger_Power_kW          27
Customer_Rating_5         25
Grid_Load_Impact_kW       18
Payment_Method             3
Session_Status             3
dtype: int64

In [17]:
df.describe(include="all")

,Session_Start,Session_ID,City,Area,Charger_Type,Energy_Delivered_kWh,Duration_Minutes,Session_Cost_INR,Wait_Time_Minutes,Battery_End_Percent,Estimated_CO2_Saved_kg,Charger_Power_kW,Customer_Rating_5,Grid_Load_Impact_kW,Payment_Method,Session_Status
count,30,30,30,30,30,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.00000,30,30
unique,30,30,7,30,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3
top,2026-09-01 07:42,EVS001,Chennai,T Nagar,Fast DC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,App,Completed
freq,1,1,6,1,15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15,26
mean,NaN,NaN,NaN,NaN,NaN,24.633333,11.863333,485.466667,28.966667,76.733333,4.566667,14.816667,3.260000,1.04000,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,18.921313,8.451994,372.779748,15.075633,14.552955,2.564793,10.685539,1.426014,0.92386,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000,36.000000,0.000000,0.000000,0.000000,0.00000,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,9.625000,5.325000,191.500000,18.250000,69.500000,2.725000,6.500000,2.350000,0.30000,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,13.500000,7.350000,265.000000,27.500000,79.500000,3.650000,9.250000,2.950000,0.50000,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,42.125000,19.025000,808.500000,38.750000,87.500000,6.775000,24.375000,4.475000,1.77500,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,59.000000,27.800000,1182.000000,61.000000,96.000000,9.000000,34.000000,5.300000,2.80000,NaN,NaN

In [19]:
df.duplicated().sum()

np.int64(0)

In [31]:
df["Charging_Efficiency"] = (
    df["Energy_Delivered_kWh"] / df["Duration_Minutes"].replace(0, 1)
)

In [32]:
print(df[["Session_ID", "Energy_Delivered_kWh",
          "Duration_Minutes", "Charging_Efficiency"]].head(10))

  Session_ID  Energy_Delivered_kWh  Duration_Minutes  Charging_Efficiency
0     EVS001                  42.5              18.2             2.335165
1     EVS002                  11.0               6.4             1.718750
2     EVS003                  55.0              25.1             2.191235
3     EVS004                   9.5               5.2             1.826923
4     EVS005                  36.0              16.8             2.142857
5     EVS006                  13.0               7.1             1.830986
6     EVS007                  48.0              22.7             2.114537
7     EVS008                   7.0               3.8             1.842105
8     EVS009                  51.5              23.6             2.182203
9     EVS010                  10.5               5.9             1.779661

In [33]:
df.to_csv("ev_charging_sessions.csv", index=False)

In [34]:
efficiency_array = df["Charging_Efficiency"].to_numpy()

print(efficiency_array)
print(type(efficiency_array))

[2.33516484 1.71875    2.19123506 1.82692308 2.14285714 1.83098592
 2.11453744 1.84210526 2.18220339 1.77966102 2.15686275 1.76470588
 0.         1.84782609 2.20689655 1.84210526 2.12230216 1.91176471
 2.15469613 1.75438596 2.10045662 1.875      2.16981132 1.82926829
 0.         1.82539683 2.13709677 1.82926829 2.12435233 1.8115942 ]
<class 'numpy.ndarray'>

In [35]:
print("Number of dimensions",efficiency_array.ndim)

Number of dimensions 1

In [36]:
print("Array Shape",efficiency_array.shape)

Array Shape (30,)

In [37]:
print("Total Elements",efficiency_array.size)

Total Elements 30

In [38]:
np.sum(efficiency_array)

np.float64(55.42821329724495)

In [39]:
print(np.sum(efficiency_array))

55.42821329724495

In [40]:
efficiency_array

array([2.33516484, 1.71875   , 2.19123506, 1.82692308, 2.14285714,
       1.83098592, 2.11453744, 1.84210526, 2.18220339, 1.77966102,
       2.15686275, 1.76470588, 0.        , 1.84782609, 2.20689655,
       1.84210526, 2.12230216, 1.91176471, 2.15469613, 1.75438596,
       2.10045662, 1.875     , 2.16981132, 1.82926829, 0.        ,
       1.82539683, 2.13709677, 1.82926829, 2.12435233, 1.8115942 ])

In [42]:
df[df["Energy_Delivered_kWh"] > 30]

,Session_Start,Session_ID,City,Area,Charger_Type,Energy_Delivered_kWh,Duration_Minutes,Session_Cost_INR,Wait_Time_Minutes,Battery_End_Percent,Estimated_CO2_Saved_kg,Charger_Power_kW,Customer_Rating_5,Grid_Load_Impact_kW,Payment_Method,Session_Status,Charging_Efficiency
0,2026-09-01 07:42,EVS001,Chennai,T Nagar,Fast DC,42.5,18.2,774,38,82,6.8,24.5,4.2,1.8,App,Completed,2.335165
2,2026-09-01 09:25,EVS003,Hyderabad,Hitech City,Fast DC,55.0,25.1,1067,19,91,8.4,31.0,5.0,2.6,App,Completed,2.191235
4,2026-09-01 11:48,EVS005,Mumbai,BKC,Fast DC,36.0,16.8,714,31,77,6.2,21.0,4.6,1.4,App,Completed,2.142857
6,2026-09-01 13:40,EVS007,Delhi,Saket,Fast DC,48.0,22.7,965,53,84,7.5,28.0,4.8,2.2,App,Completed,2.114537
8,2026-09-01 15:32,EVS009,Bengaluru,Whitefield,Fast DC,51.5,23.6,1003,28,93,8.1,30.0,5.0,2.5,App,Completed,2.182203
10,2026-09-02 07:35,EVS011,Hyderabad,Gachibowli,Fast DC,44.0,20.4,867,17,86,7.0,26.0,4.4,2.0,App,Completed,2.156863
14,2026-09-02 11:19,EVS015,Kochi,Fort Kochi,Fast DC,32.0,14.5,616,14,81,5.4,18.0,4.0,1.2,App,Completed,2.206897
16,2026-09-02 13:26,EVS017,Bengaluru,Electronic City,Fast DC,59.0,27.8,1182,44,96,9.0,34.0,5.3,2.8,App,Completed,2.122302
18,2026-09-02 15:37,EVS019,Pune,Wakad,Fast DC,39.0,18.1,769,36,83,6.4,23.0,4.5,1.6,App,Completed,2.154696
20,2026-09-03 07:58,EVS021,Delhi,Connaught Place,Fast DC,46.0,21.9,931,61,89,7.3,27.0,4.9,2.1,App,Completed,2.100457
22,2026-09-03 09:17,EVS023,Kochi,Edappally,Fast DC,34.5,15.9,676,23,80,5.8,20.0,4.1,1.3,App,Completed,2.169811
26,2026-09-03 13:49,EVS027,Mumbai,Lower Parel,Fast DC,53.0,24.8,1054,42,92,8.6,32.0,5.2,2.7,App,Completed,2.137097
28,2026-09-03 16:02,EVS029,Chennai,Anna Nagar,Fast DC,41.0,19.3,820,29,85,6.7,24.0,4.3,1.7,RFID,Completed,2.124352

In [43]:
df[df["City"] == "Chennai"]

,Session_Start,Session_ID,City,Area,Charger_Type,Energy_Delivered_kWh,Duration_Minutes,Session_Cost_INR,Wait_Time_Minutes,Battery_End_Percent,Estimated_CO2_Saved_kg,Charger_Power_kW,Customer_Rating_5,Grid_Load_Impact_kW,Payment_Method,Session_Status,Charging_Efficiency
0,2026-09-01 07:42,EVS001,Chennai,T Nagar,Fast DC,42.5,18.2,774,38,82,6.8,24.5,4.2,1.8,App,Completed,2.335165
5,2026-09-01 12:16,EVS006,Chennai,OMR,AC,13.0,7.1,256,16,88,3.5,9.0,2.9,0.5,RFID,Completed,1.830986
9,2026-09-01 16:11,EVS010,Chennai,Adyar,AC,10.5,5.9,212,24,72,2.9,7.0,2.6,0.4,RFID,Completed,1.779661
15,2026-09-02 12:47,EVS016,Chennai,Velachery,AC,14.0,7.6,274,33,90,3.8,9.5,3.0,0.5,QR,Completed,1.842105
21,2026-09-03 08:31,EVS022,Chennai,Guindy,AC,9.0,4.8,173,18,67,2.5,6.0,2.3,0.3,RFID,Completed,1.875000
28,2026-09-03 16:02,EVS029,Chennai,Anna Nagar,Fast DC,41.0,19.3,820,29,85,6.7,24.0,4.3,1.7,RFID,Completed,2.124352

In [44]:
df.groupby("City")["Energy_Delivered_kWh"].sum()

City
Bengaluru    149.0
Chennai      130.0
Delhi        110.0
Hyderabad    105.5
Kochi         73.5
Mumbai        99.0
Pune          72.0
Name: Energy_Delivered_kWh, dtype: float64

In [45]:
np.min(efficiency_array)

np.float64(0.0)

In [46]:
np.max(efficiency_array)

np.float64(2.3351648351648353)

In [47]:
np.mean(efficiency_array)

np.float64(1.847607109908165)

In [48]:
type(efficiency_array)

numpy.ndarray

In [49]:
np.sum(efficiency_array)

np.float64(55.42821329724495)

In [50]:
df["Session_Start"] = pd.to_datetime(df["Session_Start"])

In [51]:
result = df.groupby("Session_Start")["Energy_Delivered_kWh"].sum()

In [52]:
result

Session_Start
2026-09-01 07:42:00    42.5
2026-09-01 08:10:00    11.0
2026-09-01 09:25:00    55.0
2026-09-01 10:03:00     9.5
2026-09-01 11:48:00    36.0
2026-09-01 12:16:00    13.0
2026-09-01 13:40:00    48.0
2026-09-01 14:05:00     7.0
2026-09-01 15:32:00    51.5
2026-09-01 16:11:00    10.5
2026-09-02 07:35:00    44.0
2026-09-02 08:52:00    12.0
2026-09-02 09:44:00     0.0
2026-09-02 10:28:00     8.5
2026-09-02 11:19:00    32.0
2026-09-02 12:47:00    14.0
2026-09-02 13:26:00    59.0
2026-09-02 14:51:00     6.5
2026-09-02 15:37:00    39.0
2026-09-02 17:04:00    10.0
2026-09-03 07:58:00    46.0
2026-09-03 08:31:00     9.0
2026-09-03 09:17:00    34.5
2026-09-03 10:46:00    15.0
2026-09-03 11:54:00     0.0
2026-09-03 12:22:00    11.5
2026-09-03 13:49:00    53.0
2026-09-03 14:33:00     7.5
2026-09-03 16:02:00    41.0
2026-09-03 17:26:00    12.5
Name: Energy_Delivered_kWh, dtype: float64